#!/bin/bash
# Script to add a user to Linux system
if [ $(id -u) -eq 0 ]; then
	read -p "Enter username : " username
	read -s -p "Enter password : " password
	egrep "^$username" /etc/passwd >/dev/null
	if [ $? -eq 0 ]; then
		echo "$username exists!"
		exit 1
	else
		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
		useradd -m -p $pass $username
		[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
	fi
else
	echo "Only root may add a user to the system"
	exit 2
fi





$ ./adduser.sh





====
#!/usr/bin/perl -w
# Script for adding new users, giving a generic passwd
# and setting them up appropriately in /etc/sudoers
# Sudoers for the DBA's
#
# ***Declare Variables***
#
        print "Please enter a username to create\n";
	my $username = <STDIN>;
        	chomp ($username);
#
        	print "Please enter the users Real Name\n";
	my $realname = <STDIN>;
        	chomp ($realname);
# ***End Variables***
# Setup hashes
#
	my %useraddcmd = 
	(
        	useradd => "/usr/sbin/useradd $username -g users -c \"$realname\"",
	        passwd => "/sbin/passwd \"$username\"",
		groupadd => "/usr/sbin/groupadd -f dba",
	
	);

# End hashes
# Now on to add the actual username
#
      		  print "
            
            
